# Generated by Django 5.2.5 on 2026-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=200)),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=60)),
                ('ans', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('mobno', models.BigIntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
